### ISSUE TITLE
lab 1.1

### ISSUE THREAD

**Issue by strawberry321** [AreteQin/MECH370#1]
How do I change my code in order to get the diplacement/velocity graph in section 1.1 with respect to the position? Do I need to change the code to get only one B value instead of the first graph that we got?

**Comment by AreteQin** [comment]
Hi

You do not need to change the code for 1.1 and 1.2. You just need to change the simulink model and simscape model.

The displacement and position is the same thing, so the only thing you need to do is to add another signal to your scope. Pls read the [this](https://github.com/AreteQin/MECH370/blob/main/lab1.md#how-to-connect-multiple-signals-to-a-scope) to learn how to do it.

Hope it helps.
