### ISSUE TITLE
MATLAB Question - Lab4

### ISSUE THREAD

**Issue by EngineeringGuy123** [AreteQin/MECH370#10]
What is the block that says "Lab #3 DC Motor" called? And what do we put in it?
![lab4-question](https://github.com/AreteQin/MECH370/assets/140431296/e4ae1547-35c0-443c-afff-08618f27cdc3)

**Comment by EngineeringGuy123** [comment]
And where did you get the value 57.3248 from?

**Comment by AreteQin** [comment]
Hi

You need to build this inside subsystem which is from your lab3.
57.3248 is to calculate degree from radian, 180/pi = 57.3248

**Comment by EngineeringGuy123** [comment]
Ok I see. So then how would I attach that to the block diagram in the screenshot I sent? Through the input and output blocks?

**Comment by AreteQin** [comment]
Yes, you can see them outside the subsystem as well.

**Comment by EngineeringGuy123** [comment]
One more thing, are the values of theta from the lab in radians? Because the oscilloscope values are in volts.

**Comment by AreteQin** [comment]
We used a potentiometer to measure the theta. And the potentiometer is connected to -5V and 5V. Therefore, you can say that -180 degrees or -pi rad is -5V and 180 degrees or pi rad is 5V.
