### ISSUE TITLE
Lab #4 Km Value for Omega_n

### ISSUE THREAD

**Issue by Student12344** [AreteQin/MECH370#11]
Since the Km value depends on our Kp and we have two Kp values, do we use seperate Kp values or an average of both in order to find the theoretical Omega (w_n).

**Comment by AreteQin** [comment]
Yes, you need to use both to calculate k_m. But w_n is not related to k_m. Check equations on page 40.

**Comment by Student12344** [comment]
On page 39 w_n = start(Km/N*tau_m). Is it okay if I use the respective Kp values from gain 3 and 5 for Km thus having two theoretical w_n. Then I can comment on their respective error percentages for each.

**Comment by AreteQin** [comment]
Yes, it make sense.

**Comment by Student12344** [comment]
Also is Percent Overshoot PO equal to theta_1?

**Comment by AreteQin** [comment]
PO is $\theta_1/\theta_{ss}$

**Comment by Student12344** [comment]
But what is theta_ss? Where can I find what theta_ss is equal to?

**Comment by AreteQin** [comment]
$$\theta_{ss} = CH2_{p-p} - \theta_1$$

**Comment by Student12344** [comment]
So CH2_(p-p) is simply the value of CH2 we got from the experimental graphs right?
