### ISSUE TITLE
scope problem

### ISSUE THREAD

**Issue by strawberry321** [AreteQin/MECH370#12]
I built the model as shown for the simscape but the scope doesn't seem to display anything. What is wrong with the code?
R=2.04;
L=1.49e-3;
J=2.8e-6;
B=1.9e-4;
Kb=1.94e-2;
KT=1.94e-2;
Kp=7.094;
sim('Simscapelab4v3');

**Comment by AreteQin** [comment]
Hi
If you wanna use Matlab code to run your model, you need to output the data from simulink and plot it in matlab code, same as what we did in the first lab.

**Comment by strawberry321** [comment]
Is the code optional for Simscape? If so, how do I change my value of Kp?

**Comment by AreteQin** [comment]
Change from your simscape model, Kp controller block
![image](https://github.com/AreteQin/MECH370/assets/38554510/b027fcf1-f34d-4282-92c3-a87f4f7f37b4)

**Comment by strawberry321** [comment]
Now that I am not associating a code to it and just changed the values from the Kp controller while changing the name of the file, it gives this message:
Error evaluating parameter ['inertia'](matlab:Simulink.internal.OpenBlockParamsDialog(['Simscapemodel/Inertia'],'inertia');) in '[Simscapemodel/Inertia](matlab:open_and_hilite_hyperlink ('Simscapemodel/Inertia','error'))'
Caused by:
Unrecognized function or variable 'J'.
Variable 'J' has been deleted from base workspace.
Suggested Actions
Load a file into base workspace.
Fix
Create a new variable.

**Comment by strawberry321** [comment]
Here is a screenshot

![Screenshot (33)](https://github.com/AreteQin/MECH370/assets/139276575/f6644053-a4c3-49e2-8653-d0463607858f)

**Comment by Jonnn28** [comment]
not sure if this makes a difference but your "Add" block is different to the one in the PPT. you should also reduce the run time to .2 or .3 seconds
