### ISSUE TITLE
Underdamping problem on Simscape and Simulink for large value of Kp

### ISSUE THREAD

**Issue by badmo05** [AreteQin/MECH370#13]
when I input the values of kP from the experiment (8.463) on either Simulink or Simscape, the graph shows an unstable system. I followed every step as described. It only works for small gain between 1 & 4. 

![image](https://github.com/AreteQin/MECH370/assets/141341765/466ab5d6-9f63-4ac3-b891-9e5d0524151a)

(![image](https://github.com/AreteQin/MECH370/assets/141341765/b6da22a4-13b3-4358-bef2-adb4fcc8818e))

**Comment by AreteQin** [comment]
Please double check you have set the correct parameters.

**Comment by badmo05** [comment]
I do have the correct parameters, the same as lab 3. The problem arise only for Kp>5

**Comment by AreteQin** [comment]
Here are the reference values of the parameters:
L = 1.49e-3;
R = 2.04;
Kt = 2*60/(1000*2*pi);
Kb = 1.94e-2;
B = 1.9e-4; 
J = 2.8e-6;

**Comment by Jonnn28** [comment]
my simulation is exhibiting the same behaviour, also for values of kp > 5. Parameters match those listed above, tho I dont think Kt fits anywhere?

**Comment by AreteQin** [comment]
Sorry kt is 
$$ 
K_t = 2*60/(1000*2*\pi) 
$$

**Comment by AreteQin** [comment]
Sorry, there is sth wrong with GitHub. kt should be 
![image](https://github.com/AreteQin/MECH370/assets/38554510/5394ca7d-afc7-46df-bd28-48868eddd80e)
