### ISSUE TITLE
Lab 6_Simscape graphs

### ISSUE THREAD

**Issue by Kaur370** [AreteQin/MECH370#17]
Hello,
For lab 6 Simscape how many graphs do we need for each circuit: LPF, Single Section RC, and Double Resonance?
I mean in the ppt file they show 5 graphs for the frequencies of 1KHz, 5, 10,15, and 20Khz for each circuit. So do we need only one plot at 1KHz or 5 plots for 5 different frequencies?

**Comment by Kaur370** [comment]
One more question about bode diagrams: 
In the ppt file, it says to plot the bode diagram for figure 6.2_LPF, 6.4_Single section RC, and 6.6. However, lab manual question 5 says to plot the bode diagram for Figure 6.4 only. So, which one do we need to follow? 
I have attached the photos for reference.
![Lab 6_lab manual](https://github.com/AreteQin/MECH370/assets/141048135/514ffeb7-6fa9-48ad-bb54-bfbc63b8b439)
![Lab_6 ppt](https://github.com/AreteQin/MECH370/assets/141048135/4c00945f-32f1-4719-89e2-73f1e3820174)

**Comment by AreteQin** [comment]
Hi

Yes, you only compare 1,5,15 and 20KHz.

Please follow the manual.

**Comment by Kaur370** [comment]
Do you mean we need 5 graphs for each circuit instead of 1 graph at 1KHz?

**Comment by AreteQin** [comment]
The answer to this question is inside Q3 itself. Please read the manual carefully.
