### ISSUE TITLE
Mass=0

### ISSUE THREAD

**Issue by Student12344** [AreteQin/MECH370#2]
For the mass = 0, the Gain 1/M is not possible if M=0. Does that mean I eliminate the Mass Gain in my simulink in order Question #3 from Exercise 1.1 from the Lab. Is the same step done for Question #3 for the simscape exercise?

**Comment by AreteQin** [comment]
Hi 
It’s a typo. So you don’t need change the model, just set M = 0.01.

Hope this helps.
