### ISSUE TITLE
Different blocks

### ISSUE THREAD

**Issue by paritoasted** [AreteQin/MECH370#4]
There are blocks on MATLAB and the ppt are a little different what should I do?
![image](https://github.com/AreteQin/MECH370/assets/105744609/e760097d-ae29-4d3e-bb08-219a9563ee7d)
![image](https://github.com/AreteQin/MECH370/assets/105744609/6e38811c-eadf-4a85-8564-2eee487f2c41)
![image](https://github.com/AreteQin/MECH370/assets/105744609/8a728a88-e8c1-4f8d-a6a5-9c3e5ad1aeab)
![image](https://github.com/AreteQin/MECH370/assets/105744609/fdd2ee3d-1d29-42fd-83cb-b121fcebf558)

the first 2 are from the matlab and the last 2 from ppt

**Comment by AreteQin** [comment]
Pls double click the "Local Restriction" block and change the type to Fixed. 

![image](https://github.com/AreteQin/MECH370/assets/38554510/edde9923-06a3-4d24-9a78-dc3db2837c76)

**Comment by paritoasted** [comment]
![image](https://github.com/AreteQin/MECH370/assets/105744609/5554e96c-45b3-4620-b2f9-ab1100e09533)
I see this after double clicking
