### ISSUE TITLE
Experimental results pont 4

### ISSUE THREAD

**Issue by MarkMaarawi** [AreteQin/MECH370#5]
It requires us to find the Reynolds’s number with the given formula, but the formula requires a fluid velocity (v). I’m not sure how to find this value. Is it the q max?

**Comment by AreteQin** [comment]
Hi

You can calculate the velocity using:
$$v = q/A$$

where A is the cross-sectional area of the capillary
$$A= \pi (\frac{D}{2})^2$$

where D is the diameter of the capillary.

**Comment by MarkMaarawi** [comment]
Thank you, the number makes much more sense now.
