### ISSUE TITLE
Lab 3 part 2 table

### ISSUE THREAD

**Issue by moksw** [AreteQin/MECH370#6]
I’m not sure how to find the motor angular velocity. I end up with values that don’t seem to make sense. I took the value from the Back-EMF constant (either [V/krpm] or [V/rad/s]) and get values around 1560rpm or 164rad/s. I’m dividing the Tacho Ch2 voltage with the constants on the spec sheet. Am I using the wrong values in my equation?

![image](https://github.com/AreteQin/MECH370/assets/93796636/ebe2d34b-66be-407a-aab8-6b7af2510db0)

Also what exactly is the motor constant? I don’t really understand which values would give us a constant.

**Comment by AreteQin** [comment]
For angular velocity, pls check this out: https://github.com/AreteQin/MECH370/blob/main/lab3.md#how-to-calculate-angular-velocities-according-to-the-tachometer-voltages

For K_Motor, check equation 3-9.

**Comment by EngineeringGuy123** [comment]
> For angular velocity, pls check this out: https://github.com/AreteQin/MECH370/blob/main/lab3.md#how-to-calculate-angular-velocities-according-to-the-tachometer-voltages
> 
> For K_Motor, check equation 3-9.
