### ISSUE TITLE
Lab 3 Questions

### ISSUE THREAD

**Issue by EngineeringGuy123** [AreteQin/MECH370#7]
I just had a question in the results for lab 3.

Is the viscous damping B, 2.8 oz-in/krpm (1.9e-4N-m-s)?

**Comment by EngineeringGuy123** [comment]
Oh and from question 2, how do you determine the time constant from experimental values? I know how to find it from manufacturer's specifications but I don't understand what is meant by experimental.

**Comment by AreteQin** [comment]
Hi
Yes, viscous damping B, 2.8 oz-in/krpm (1.9e-4N-m-s). It is a typo on the manual saying it is D. 
You can calculate the average time constant from your experiments.
Hope this helps!
