### ISSUE TITLE
Lab 4 Simscape

### ISSUE THREAD

**Issue by Kaur370** [AreteQin/MECH370#9]
Hello, I made Simscape as specified in the PowerPoint file, but there is an issue related to units. As the model consists of the portion of lab 3 Simscape, the input unit is rad/sec and the output is in degrees. I tried my best but still I have a problem. Could you please help? 

![Lab 4 simscape](https://github.com/AreteQin/MECH370/assets/141048135/daa8967a-9233-4988-ba8c-6f686d16204a)

**Comment by AreteQin** [comment]
Hi
rad/s is a unit for angular velocity and degree is a unit for angular position. They are not able to be converted.

**Comment by Kaur370** [comment]
> Hi rad/s is a unit for angular velocity and degree is a unit for angular position. They are not able to be converted.

Then how we suppose to have angular position scope in Simscape? We have a portion of lab 3 simscape in the lab 4 simscape model. The lab 3 portion has resistance, inductance, and inertia values that are in radians. So, what to do with those values to have the required scope in degrees?

**Comment by AreteQin** [comment]
Pls show me a screenshot of your simscape model

**Comment by Kaur370** [comment]
> 

![Lab 4 simscape_](https://github.com/AreteQin/MECH370/assets/141048135/fbcee950-2453-483e-b8cf-c5d5018fbc57)

**Comment by AreteQin** [comment]
PS-Simulink Converter should be connected to A, instead of W

**Comment by Kaur370** [comment]
![lab 4 simscape slides](https://github.com/AreteQin/MECH370/assets/141048135/13b26456-5276-4118-9cea-d7e91aefe4aa)
When i made these changes to my simscape model it generates error related to input-output units

**Comment by AreteQin** [comment]
Even after you changed the connection to A?

**Comment by Kaur370** [comment]
Give me 2 minutes, i am trying

**Comment by Kaur370** [comment]
Its fixed, thank you

**Comment by AreteQin** [comment]
You are welcome
